[package]
name = "alertview"
version = "0.8.0"
edition = "2021"
description = "A lightweight alert dashboard for Alertmanager, Grafana and Zabbix"
license = "MIT"
repository = "https://github.com/frakev/alertview"
readme = "README.md"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
chrono = { version = "0.4", features = ["serde"] }
notify = "6"
notify-debouncer-mini = "0.4"
tower-http = { version = "0.5", features = ["compression-gzip"] }
futures = "0.3"
percent-encoding = "2"
